import { NextResponse } from "next/server";
import { z } from "zod";
import { getDb } from "@/lib/mongodb";
import { getCurrentUser, assertProjectOwner } from "@/lib/auth";
import { captureSnapshot } from "@/lib/snapshots";

const ExportReqSchema = z.object({
  format: z.enum(["markdown", "json", "agent_pack", "cursorrules"]).default("markdown"),
});

const NODE_TYPE_LIST = [
  "Product Overview", "Feature Scope", "User Stories", "Technical Architecture",
  "Database Schema", "API Contracts", "UI Requirements", "Acceptance Criteria",
  "AI Coding Rules", "File References", "Deployment Requirements",
  "Testing Instructions", "GitHub Context", "Prompt Output",
];

function buildCursorrules(project: any, nodes: any[]): string {
  const byType: Record<string, any[]> = {};
  for (const n of nodes) {
    if (!byType[n.type]) byType[n.type] = [];
    byType[n.type].push(n);
  }

  const repo = project.repository || {};
  const frameworks = repo.frameworks || [];
  const projectName = project.name || "this project";
  const description = (project.description || "").trim();

  const lines: string[] = [];
  let intro = `You are an expert engineer working on ${projectName}.`;
  if (frameworks.length > 0) {
    intro += ` The stack is: ${frameworks.join(", ")}.`;
  }
  lines.push(intro);
  
  if (description) {
    lines.push("");
    lines.push(description);
  }
  
  lines.push("");
  lines.push(
    "Treat the sections below as binding project intelligence — do not " +
    "contradict the architecture, conventions, or constraints encoded here. " +
    "Cite node titles when referencing existing components."
  );
  lines.push("");

  function emit(sectionTitle: string, items: any[], fallback = ""): void {
    if (items.length === 0 && !fallback) return;
    lines.push(`# ${sectionTitle}`);
    if (items.length === 0) {
      lines.push(fallback);
      lines.push("");
      return;
    }
    for (const it of items) {
      const title = (it.title || "").trim() || "(untitled)";
      const content = (it.content || "").trim();
      lines.push(`## ${title}`);
      if (content) {
        lines.push(content);
      } else {
        lines.push("_(no content)_");
      }
      lines.push("");
    }
  }

  if (frameworks.length > 0) {
    lines.push("# Stack");
    for (const f of frameworks) {
      lines.push(`- ${f}`);
    }
    if (repo.owner && repo.repo) {
      lines.push(
        `- Repo: \`${repo.owner}/${repo.repo}\` ` +
        `(branch \`${repo.branch || "main"}\`)`
      );
    }
    lines.push("");
  }

  emit("Technical Architecture", byType["Technical Architecture"] || []);
  emit("Database Schema", byType["Database Schema"] || []);
  emit("API Contracts", byType["API Contracts"] || []);
  emit("Coding Rules & Conventions", byType["AI Coding Rules"] || []);
  emit("Testing Conventions", byType["Testing Instructions"] || []);

  const allRefs: string[] = [];
  const seen = new Set<string>();
  
  for (const n of nodes) {
    const refs = n.file_references || [];
    const stale = n.metadata?.stale_file_references || [];
    const staleSet = new Set(stale);
    
    for (const f of refs) {
      if (!seen.has(f) && !staleSet.has(f)) {
        seen.add(f);
        allRefs.push(f);
      }
    }
  }

  if (allRefs.length > 0) {
    lines.push("# Key Files");
    lines.push(
      "These files are referenced by the project graph — read them " +
      "before modifying related code."
    );
    for (const f of allRefs) {
      lines.push(`- \`${f}\``);
    }
    lines.push("");
  }

  lines.push("# When generating code");
  lines.push(
    "- Follow the architecture and conventions above; do not introduce " +
    "stack choices not listed in `# Stack`."
  );
  lines.push(
    "- Reference exact file paths from `# Key Files` when they exist; " +
    "do not invent paths."
  );
  lines.push(
    "- Add or update tests for any new behaviour, mirroring the style " +
    "documented in `# Testing Conventions`."
  );
  lines.push(
    "- If a request conflicts with this file, surface the conflict " +
    "explicitly instead of silently overriding."
  );
  lines.push("");
  lines.push(`<!-- Generated by CortexFlow from project: ${projectName} -->`);

  return lines.join("\n").replace(/\r\n/g, "\n").trim() + "\n";
}

export async function POST(
  req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id: projectId } = await params;
    const user = await getCurrentUser(req);
    
    // Assert owner
    const project = await assertProjectOwner(projectId, user.id);
    const db = await getDb();
    
    const body = await req.json();
    const result = ExportReqSchema.safeParse(body);
    
    if (!result.success) {
      return NextResponse.json(
        { detail: result.error.issues.map(e => `${e.path.join(".")}: ${e.message}`).join(", ") },
        { status: 400 }
      );
    }
    
    const { format } = result.data;
    
    const nodes = await db.collection("nodes")
      .find({ project_id: projectId }, { projection: { _id: 0 } })
      .toArray();
      
    const edges = await db.collection("edges")
      .find({ project_id: projectId }, { projection: { _id: 0 } })
      .toArray();
      
    if (format === "json") {
      const jsonContent = {
        project: {
          id: project.id,
          name: project.name,
          description: project.description,
          repository: project.repository || null,
        },
        nodes,
        edges,
      };
      
      await captureSnapshot(projectId, "export", "Export · json", {
        export_format: "json",
        export_content: jsonContent,
      });
      
      return NextResponse.json({
        format: "json",
        content: jsonContent,
      });
    }
    
    if (format === "cursorrules") {
      const cursorrules = buildCursorrules(project, nodes);
      
      await captureSnapshot(projectId, "export", "Export · cursorrules", {
        export_format: "cursorrules",
        export_content: cursorrules,
      });
      
      return NextResponse.json({
        format: "cursorrules",
        content: cursorrules,
      });
    }
    
    // Format markdown
    const mdLines: string[] = [];
    mdLines.push(`# ${project.name}`);
    mdLines.push("");
    if (project.description) {
      mdLines.push(project.description);
      mdLines.push("");
    }
    
    const repo = project.repository || {};
    if (repo && repo.owner && repo.repo) {
      mdLines.push("## Repository");
      mdLines.push(`- **Repo**: \`${repo.owner}/${repo.repo}\` (branch: \`${repo.branch || "main"}\`)`);
      if (repo.frameworks && repo.frameworks.length > 0) {
        mdLines.push(`- **Detected stack**: ${repo.frameworks.join(", ")}`);
      }
      mdLines.push("");
    }
    
    const byType: Record<string, any[]> = {};
    for (const n of nodes) {
      if (!byType[n.type]) byType[n.type] = [];
      byType[n.type].push(n);
    }
    
    for (const ntype of NODE_TYPE_LIST) {
      if (!byType[ntype]) continue;
      mdLines.push(`## ${ntype}`);
      for (const n of byType[ntype]) {
        mdLines.push(`### ${n.title || "(untitled)"}`);
        if (n.content) {
          mdLines.push(n.content);
        }
        if (n.file_references && n.file_references.length > 0) {
          mdLines.push("");
          mdLines.push("**Referenced files:**");
          for (const f of n.file_references) {
            mdLines.push(`- \`${f}\``);
          }
        }
        mdLines.push("");
      }
    }
    
    if (edges.length > 0) {
      mdLines.push("## Relationships");
      const nodeIndex: Record<string, any> = {};
      nodes.forEach(n => {
        nodeIndex[n.id] = n;
      });
      for (const e of edges) {
        const s = nodeIndex[e.source_node_id]?.title || "?";
        const t = nodeIndex[e.target_node_id]?.title || "?";
        mdLines.push(`- \`${s}\` → \`${t}\` (${e.relationship_type})`);
      }
    }
    
    const markdown = mdLines.join("\n").replace(/\r\n/g, "\n");
    
    if (format === "agent_pack") {
      const agentPack =
        "# CortexFlow Agent Context Pack\n\n" +
        "You are working on the project described below. Treat this as " +
        "binding project intelligence: follow the architecture, constraints, " +
        "and conventions. Reference linked files when implementing.\n\n" +
        markdown;
        
      await captureSnapshot(projectId, "export", "Export · agent_pack", {
        export_format: "agent_pack",
        export_content: agentPack,
      });
      
      return NextResponse.json({
        format: "agent_pack",
        content: agentPack,
      });
    }
    
    // Default: markdown
    await captureSnapshot(projectId, "export", "Export · markdown", {
      export_format: "markdown",
      export_content: markdown,
    });
    
    return NextResponse.json({
      format: "markdown",
      content: markdown,
    });
  } catch (err: any) {
    const status = err.status || 500;
    return NextResponse.json({ detail: err.message || "Internal server error" }, { status });
  }
}
